Repository dwyl/imgup, pull requests merged in 2023-06, with the labels that each got.

#55 [PR] Implementing basic file upload
  .github/workflows/ci.yml
  .gitignore
  README.md
  an_aws_sam_imgup-compressor/.gitignore
  an_aws_sam_imgup-compressor/buildspec.yml
  an_aws_sam_imgup-compressor/package-lock.json
  an_aws_sam_imgup-compressor/package.json
  an_aws_sam_imgup-compressor/samconfig.toml
  an_aws_sam_imgup-compressor/src/index.js
  an_aws_sam_imgup-compressor/template.yaml
  assets/js/app.js
  lib/app_web/components/layouts/app.html.heex
  lib/app_web/components/layouts/root.html.heex
  lib/app_web/controllers/error_html.ex
  lib/app_web/controllers/error_json.ex
  lib/app_web/controllers/page_controller.ex
  lib/app_web/controllers/page_html.ex
  lib/app_web/controllers/page_html/home.html.heex
  lib/app_web/live/imgup_live.ex
  lib/app_web/live/imgup_live.html.heex
  lib/app_web/router.ex
  lib/app_web/s3_upload.ex
  mix.exs
  mix.lock
  priv/static/images/phoenix.png
  test/app_web/controllers/error_html_test.exs
  test/app_web/controllers/error_json_test.exs
  test/app_web/controllers/page_controller_test.exs
  test/app_web/live/imgup_live_test.exs
  test/support/upload_support.ex
Labels: enhancement, in-review

#61 [PR] Adding API that consumes image files
  .github/workflows/ci.yml
  .gitignore
  README.md
  api.md
  config/config.exs
  lib/app/upload.ex
  lib/app_web/controllers/api_controller.ex
  lib/app_web/controllers/api_json.ex
  lib/app_web/controllers/page_controller.ex
  lib/app_web/controllers/page_html.ex
  lib/app_web/controllers/page_html/home.html.heex
  lib/app_web/endpoint.ex
  lib/app_web/live/imgup_live.ex
  lib/app_web/live/imgup_live.html.heex
  lib/app_web/router.ex
  mix.exs
  mix.lock
  test/app/upload_test.exs
  test/app_web/api_test.exs
  test/app_web/live/imgup_live_test.exs
  test/app_web/page_test.exs
  test/test_helper.exs
Labels: enhancement, awaiting-review

#77 [PR] Fixing black borders.
  README.md
  an_aws_sam_imgup-compressor/src/index.js
Labels: bug, enhancement, awaiting-review, documentation

#79 PR: Resolve API Deployment issue #78
  .github/fly.yml
  .github/workflows/ci.yml
Labels: awaiting-review, chore, technical, tech-debt, T5m, BLOCKED

#70 PR: Fix Env Var issue #68
  config/prod.exs
  config/runtime.exs
  fly.toml
  lib/app/upload.ex
  lib/app_web/controllers/api_controller.ex
  lib/app_web/controllers/page_controller.ex
  lib/app_web/controllers/page_html/home.html.heex
  mix.exs
  mix.lock
Labels: help wanted, awaiting-review, priority-1, chore, technical, tech-debt, elixir, T5m

#81 [PR] Placing deploy Github workflow in the correct folder.
  .github/workflows/fly.yml
Labels: bug, awaiting-review, chore, BLOCKED

#83 [PR] Buckets are now fetched from env variable.
  .github/workflows/ci.yml
  config/config.exs
  lib/app/upload.ex
  lib/app_web/live/imgup_live.ex
  test/app/upload_test.exs
  test/app_web/api_test.exs
Labels: enhancement, awaiting-review, chore
